//AUTOMATICALLY GENERATED - MAY BE OVERWRITTEN
`define CWLITE 
`define NEWAEUSBCHIP 
`define UART_CLK 96000000
`define UART_BAUD 512000
`define MAX_SAMPLES 131072
`define HW_TYPE 10
`define HW_VER 0
`define SYSTEM_CLK 96000000
`define CLOCK_ADVANCED 
`define NOBUFG_ADCCLK 
`define DISABLE_FPA_IN
`define ENABLE_RECONFIG
