# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo.xci
# IP: The module: 'cwlite_shallow_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'cwlite_shallow_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cwlite_shallow_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cwlite_shallow_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo.xci
# IP: The module: 'cwlite_shallow_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'cwlite_shallow_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'cwlite_shallow_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jp/GitHub/OpenTitan/husky/fpga/vivado/cwhusky.srcs/sources_1/ip/cwlite_shallow_fifo/cwlite_shallow_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cwlite_shallow_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
